### ISSUE TITLE
Export databases results

### ISSUE THREAD

**Issue by i-guigon** [metgem/metgem#101]
Hi there!

Thank you for this software!

I have some difficulties when I try to export the database search results.

* I can export the nodes table with "Export Metadata as CSV". It works and It's OK for the "standard" results but for the "analogs" results the cell will just contain "Analogs results available", I don't have any detail.
* When I try the "Export Database results" functionality with any field separator other than "Other" (the empty cell next to it is then grey and non-clikable), when I click "OK" the empty cell next to the field separator becomes red and nothing happens if I click "OK" again.
* When I try the "Export Database results" functionality with "Other" as field separator and I put a comma or whatever in the empty cell, I get an error : 
```
Unhandled exception
It seems you have found a bug in MetGem. Please report details.
You should restart the application now.
'QLineEdit' object has no attribute 'delimiter'
```

And the details : 
```
Traceback (most recent call last):
  File "Softwares/metgem-master/metgem_app/ui/main_window.py", line 1168, in export_db_results
    filename, *values = self._dialog.getValues()
  File "Softwares/metgem-master/metgem_app/ui/export_db_results_dialog.py", line 121, in getValues
    return self.editExportFile.text(), self.editFieldSeparator.delimiter(), self.spinNumHits.value(), attributes
AttributeError: 'QLineEdit' object has no attribute 'delimiter'
```

I got this problem with last release (1.3.6) and again with the version of code on master branch that I downloaded on 03/03/2022.
I'm working on Ubuntu 20.04.

Thank you for your help !

**Comment by n-elie** [comment]
Hello,

Thanks for your bug report. It seems the `Export databases results` functionnality was broken. It should be fixed by cc874a18362a8ca3ccc7d65b1b1a61865a6406c6.
About the `Analogs results available` text for `Export Metadata as CSV` function: it is a very basic and it would be easy to confuse between standards and analogs. So this is intended.

Nicolas

**Comment by i-guigon** [comment]
Hello

Thank you for the quick fix. It seems OK now.
I've just noticed that there is some line breaks sometimes in columns "standardN_database" or "analogN_database" for MS-DIAL results, so I get stuff like this:

```
236,193.0494,0.9474,GNPS - Massbank Spectral Library (3rd Party),Massbank:FIO00950 Scopoletin M+H,0.9175,MS-DIAL - 
							BMDMS-NP,209.04,Fraxetin
237,362.2321
```

I guess the malformed characters may be in the MS-DIAL database itself, but maybe you could add a check for unwanted line breaks ?

Thank you again for your help.

**Comment by n-elie** [comment]
By the way, you should update the MS-Dial plugin to v1.3 to get rid of these unicode characters in db names
